"""add store catalog files and inventory foundation

Revision ID: 146fb74fcd9e
Revises: 4d2275bed978
Create Date: 2026-08-23 03:01:43.253742
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "146fb74fcd9e"
down_revision: str | None = "4d2275bed978"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("brand_no", sa.String(length=40), nullable=False),
        sa.Column("brand_name", sa.String(length=128), nullable=False),
        sa.Column("brand_name_normalized", sa.String(length=128), nullable=False),
        sa.Column("logo_object_key", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("brand_status", sa.String(length=16), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("brand_name_normalized", name="uk_brands_name_normalized"),
        sa.UniqueConstraint("brand_no", name="uk_brands_no"),
    )
    op.create_table(
        "categories",
        sa.Column("category_no", sa.String(length=40), nullable=False),
        sa.Column("parent_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("category_name", sa.String(length=64), nullable=False),
        sa.Column("category_code", sa.String(length=64), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("icon_object_key", sa.String(length=512), nullable=True),
        sa.Column("category_status", sa.String(length=16), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["categories.id"], name=op.f("fk_categories_parent_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("category_code", name="uk_categories_code"),
        sa.UniqueConstraint("category_no", name="uk_categories_no"),
    )
    op.create_index(
        "idx_categories_parent_sort", "categories", ["parent_id", "sort_order", "id"], unique=False
    )
    op.create_table(
        "file_upload_sessions",
        sa.Column("upload_no", sa.String(length=40), nullable=False),
        sa.Column("uploader_user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("target_owner_type", sa.String(length=32), nullable=False),
        sa.Column("target_owner_no", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("reserved_bucket", sa.String(length=64), nullable=False),
        sa.Column("reserved_object_key", sa.String(length=512), nullable=False),
        sa.Column("upload_type", sa.String(length=16), nullable=False),
        sa.Column("provider_upload_id", sa.String(length=256), nullable=True),
        sa.Column(
            "active_provider_upload_id",
            sa.String(length=256),
            sa.Computed(
                "CASE WHEN upload_status IN ('created','uploading','uploaded') "
                "THEN provider_upload_id ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("expected_mime_types", sa.JSON(), nullable=False),
        sa.Column("max_size_bytes", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("expected_sha256", sa.BINARY(length=32), nullable=True),
        sa.Column("part_manifest", sa.JSON(), nullable=True),
        sa.Column("upload_status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("aborted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["uploader_user_id"],
            ["users.id"],
            name=op.f("fk_file_upload_sessions_uploader_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_upload_sessions")),
        sa.UniqueConstraint(
            "provider", "active_provider_upload_id", name="uk_upload_active_provider_id"
        ),
        sa.UniqueConstraint(
            "reserved_bucket", "reserved_object_key", name="uk_upload_reserved_object"
        ),
        sa.UniqueConstraint("upload_no", name="uk_file_upload_sessions_no"),
    )
    op.create_index(
        "idx_upload_sessions_expiry",
        "file_upload_sessions",
        ["upload_status", "expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_upload_sessions_user_status",
        "file_upload_sessions",
        ["uploader_user_id", "upload_status", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "stores",
        sa.Column("store_no", sa.String(length=40), nullable=False),
        sa.Column("owner_user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("store_name", sa.String(length=128), nullable=False),
        sa.Column("store_name_normalized", sa.String(length=128), nullable=False),
        sa.Column("logo_object_key", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("store_status", sa.String(length=32), nullable=False),
        sa.Column("service_phone_ciphertext", sa.VARBINARY(length=512), nullable=True),
        sa.Column(
            "rating_score", mysql.DECIMAL(precision=3, scale=2), server_default="0", nullable=False
        ),
        sa.Column("rating_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column(
            "follower_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False
        ),
        sa.Column("sales_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("suspended_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_stores_owner_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("store_name_normalized", name="uk_stores_name_normalized"),
        sa.UniqueConstraint("store_no", name="uk_stores_store_no"),
    )
    op.create_index("idx_stores_owner", "stores", ["owner_user_id"], unique=False)
    op.create_index(
        "idx_stores_status_created", "stores", ["store_status", "created_at", "id"], unique=False
    )
    op.create_table(
        "file_objects",
        sa.Column("file_no", sa.String(length=40), nullable=False),
        sa.Column("bucket", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("owner_type", sa.String(length=32), nullable=False),
        sa.Column("owner_no", sa.String(length=64), nullable=False),
        sa.Column("upload_session_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("parent_file_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("variant", sa.String(length=32), nullable=False),
        sa.Column("processor_version", sa.String(length=32), nullable=True),
        sa.Column("original_filename_ciphertext", sa.VARBINARY(length=1024), nullable=True),
        sa.Column("declared_mime_type", sa.String(length=128), nullable=False),
        sa.Column("detected_mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("sha256", sa.BINARY(length=32), nullable=False),
        sa.Column("provider_checksum", sa.String(length=128), nullable=True),
        sa.Column("width", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("height", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("duration_ms", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("page_count", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("sensitivity_level", sa.String(length=4), nullable=False),
        sa.Column("scan_status", sa.String(length=16), nullable=False),
        sa.Column("file_status", sa.String(length=16), nullable=False),
        sa.Column("storage_version_id", sa.String(length=128), nullable=True),
        sa.Column("encryption_key_version", sa.SmallInteger(), nullable=True),
        sa.Column(
            "reference_count", mysql.INTEGER(unsigned=True), server_default="0", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_file_id"],
            ["file_objects.id"],
            name=op.f("fk_file_objects_parent_file_id_file_objects"),
        ),
        sa.ForeignKeyConstraint(
            ["upload_session_id"],
            ["file_upload_sessions.id"],
            name=op.f("fk_file_objects_upload_session_id_file_upload_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_objects")),
        sa.UniqueConstraint("bucket", "object_key", name="uk_file_objects_storage_key"),
        sa.UniqueConstraint("file_no", name="uk_file_objects_no"),
        sa.UniqueConstraint(
            "parent_file_id", "variant", "processor_version", name="uk_file_derived_variant"
        ),
    )
    op.create_index("idx_file_objects_hash", "file_objects", ["sha256", "size_bytes"], unique=False)
    op.create_index(
        "idx_file_objects_lifecycle",
        "file_objects",
        ["file_status", "expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_file_objects_owner",
        "file_objects",
        ["owner_type", "owner_no", "file_status", "id"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("product_no", sa.String(length=40), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("category_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("brand_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("subtitle", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("current_detail_content_version_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column(
            "published_detail_content_version_id", mysql.BIGINT(unsigned=True), nullable=True
        ),
        sa.Column("product_status", sa.String(length=32), nullable=False),
        sa.Column("default_sku_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column(
            "min_price_amount", mysql.BIGINT(unsigned=True), server_default="0", nullable=False
        ),
        sa.Column(
            "max_price_amount", mysql.BIGINT(unsigned=True), server_default="0", nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sales_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column("review_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column(
            "rating_score", mysql.DECIMAL(precision=3, scale=2), server_default="0", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("off_shelf_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_products_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_products_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["current_detail_content_version_id"],
            ["product_content_versions.id"],
            name="fk_products_current_content_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["default_sku_id"],
            ["product_skus.id"],
            name="fk_products_default_sku",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["published_detail_content_version_id"],
            ["product_content_versions.id"],
            name="fk_products_published_content_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_products_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("product_no", name="uk_products_product_no"),
    )
    op.create_index(
        "idx_products_category_status",
        "products",
        ["category_id", "product_status", "id"],
        unique=False,
    )
    op.create_index(
        "idx_products_store_status",
        "products",
        ["store_id", "product_status", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "shipping_templates",
        sa.Column("template_no", sa.String(length=40), nullable=False),
        sa.Column("template_family_no", sa.String(length=40), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("template_name", sa.String(length=128), nullable=False),
        sa.Column("delivery_type", sa.String(length=32), nullable=False),
        sa.Column("charge_mode", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("template_status", sa.String(length=16), nullable=False),
        sa.Column("dispatch_min_hours", sa.SmallInteger(), nullable=False),
        sa.Column("dispatch_max_hours", sa.SmallInteger(), nullable=False),
        sa.Column("policy_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column(
            "current_template_family_no",
            sa.String(length=40),
            sa.Computed(
                "CASE WHEN template_status = 'effective' THEN template_family_no ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "dispatch_min_hours <= dispatch_max_hours",
            name=op.f("ck_shipping_templates_shipping_dispatch_range"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_shipping_templates_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipping_templates")),
        sa.UniqueConstraint(
            "store_id", "current_template_family_no", name="uk_shipping_template_current_family"
        ),
        sa.UniqueConstraint(
            "template_family_no", "policy_version", name="uk_shipping_template_family_version"
        ),
        sa.UniqueConstraint("template_no", name="uk_shipping_templates_no"),
    )
    op.create_table(
        "store_announcements",
        sa.Column("announcement_no", sa.String(length=40), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("announcement_status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_announcements_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_announcements")),
        sa.UniqueConstraint("announcement_no", name="uk_store_announcements_no"),
    )
    op.create_index(
        "idx_store_announcements_public",
        "store_announcements",
        ["store_id", "announcement_status", "starts_at", "ends_at", "sort_order"],
        unique=False,
    )
    op.create_table(
        "store_categories",
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("category_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("approval_status", sa.String(length=16), nullable=False),
        sa.Column("approved_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_store_categories_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_store_categories_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_categories_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_categories")),
        sa.UniqueConstraint("store_id", "category_id", name="uk_store_categories_store_category"),
    )
    op.create_table(
        "store_certifications",
        sa.Column("certification_no", sa.String(length=40), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("certification_type", sa.String(length=32), nullable=False),
        sa.Column("subject_name_ciphertext", sa.VARBINARY(length=1024), nullable=False),
        sa.Column("certificate_no_ciphertext", sa.VARBINARY(length=1024), nullable=False),
        sa.Column("certificate_no_hash", sa.BINARY(length=32), nullable=True),
        sa.Column(
            "current_material_version",
            mysql.INTEGER(unsigned=True),
            server_default="1",
            nullable=False,
        ),
        sa.Column("evidence_object_key", sa.String(length=512), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("reviewed_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("decision_reason_code", sa.String(length=64), nullable=True),
        sa.Column("decision_reason", sa.String(length=1000), nullable=True),
        sa.Column("resubmitted_at", sa.DateTime(), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_store_certifications_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_certifications_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_certifications")),
        sa.UniqueConstraint("certification_no", name="uk_store_certifications_no"),
    )
    op.create_index(
        "idx_store_cert_expiry",
        "store_certifications",
        ["review_status", "valid_until"],
        unique=False,
    )
    op.create_index(
        "idx_store_cert_store_type",
        "store_certifications",
        ["store_id", "certification_type", "review_status"],
        unique=False,
    )
    op.create_table(
        "store_follows",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("followed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "active_user_id",
            mysql.BIGINT(unsigned=True),
            sa.Computed(
                "CASE WHEN deleted_at IS NULL THEN user_id ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_follows_store_id_stores")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_store_follows_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_follows")),
        sa.UniqueConstraint("store_id", "active_user_id", name="uk_store_follows_active_user"),
    )
    op.create_index(
        "idx_store_follows_user",
        "store_follows",
        ["user_id", "deleted_at", "followed_at"],
        unique=False,
    )
    op.create_table(
        "store_product_groups",
        sa.Column("group_no", sa.String(length=40), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("parent_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("group_name", sa.String(length=64), nullable=False),
        sa.Column("group_name_normalized", sa.String(length=64), nullable=False),
        sa.Column("group_status", sa.String(length=16), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "active_parent_scope_id",
            mysql.BIGINT(unsigned=True),
            sa.Computed(
                "CASE WHEN group_status = 'active' THEN COALESCE(parent_id, 0) ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column(
            "active_group_name_normalized",
            sa.String(length=64),
            sa.Computed(
                "CASE WHEN group_status = 'active' THEN group_name_normalized ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["store_product_groups.id"],
            name=op.f("fk_store_product_groups_parent_id_store_product_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_product_groups_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_product_groups")),
        sa.UniqueConstraint("group_no", name="uk_store_product_groups_no"),
        sa.UniqueConstraint(
            "store_id",
            "active_parent_scope_id",
            "active_group_name_normalized",
            name="uk_store_product_groups_active_name",
        ),
    )
    op.create_index(
        "idx_store_groups_navigation",
        "store_product_groups",
        ["store_id", "group_status", "parent_id", "sort_order", "id"],
        unique=False,
    )
    op.create_table(
        "store_service_policies",
        sa.Column("policy_no", sa.String(length=40), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("policy_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content", mysql.MEDIUMTEXT(), nullable=False),
        sa.Column("content_hash", sa.BINARY(length=32), nullable=False),
        sa.Column("policy_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("policy_status", sa.String(length=16), nullable=False),
        sa.Column("effective_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(), nullable=True),
        sa.Column("supersedes_policy_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("created_by", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("published_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("withdrawn_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_store_service_policies_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_store_service_policies_published_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_service_policies_store_id_stores")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_policy_id"],
            ["store_service_policies.id"],
            name=op.f("fk_store_service_policies_supersedes_policy_id_store_service_policies"),
        ),
        sa.ForeignKeyConstraint(
            ["withdrawn_by"],
            ["users.id"],
            name=op.f("fk_store_service_policies_withdrawn_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_service_policies")),
        sa.UniqueConstraint("policy_no", name="uk_store_service_policies_no"),
        sa.UniqueConstraint(
            "store_id", "policy_type", "policy_version", name="uk_store_policy_family_version"
        ),
    )
    op.create_index(
        "idx_store_policy_public",
        "store_service_policies",
        ["store_id", "policy_type", "policy_status", "effective_at", "expires_at"],
        unique=False,
    )
    op.create_table(
        "admin_batch_jobs",
        sa.Column("job_no", sa.String(length=40), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("requested_by", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("scope_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("permission_code", sa.String(length=128), nullable=False),
        sa.Column("input_file_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("request_config", sa.JSON(), nullable=False),
        sa.Column("request_hash", sa.BINARY(length=32), nullable=False),
        sa.Column("job_status", sa.String(length=16), nullable=False),
        sa.Column("execution_backend", sa.String(length=32), nullable=True),
        sa.Column("execution_job_no", sa.String(length=40), nullable=True),
        sa.Column(
            "execution_status_version",
            mysql.BIGINT(unsigned=True),
            server_default="0",
            nullable=False,
        ),
        sa.Column("total_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column("success_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column("failure_count", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_requested_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=500), nullable=True),
        sa.Column("result_file_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("error_file_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["cancel_requested_by"],
            ["users.id"],
            name=op.f("fk_admin_batch_jobs_cancel_requested_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["error_file_id"],
            ["file_objects.id"],
            name=op.f("fk_admin_batch_jobs_error_file_id_file_objects"),
        ),
        sa.ForeignKeyConstraint(
            ["input_file_id"],
            ["file_objects.id"],
            name=op.f("fk_admin_batch_jobs_input_file_id_file_objects"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_admin_batch_jobs_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["result_file_id"],
            ["file_objects.id"],
            name=op.f("fk_admin_batch_jobs_result_file_id_file_objects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_batch_jobs")),
        sa.UniqueConstraint(
            "execution_backend", "execution_job_no", name="uk_admin_batch_jobs_execution"
        ),
        sa.UniqueConstraint("job_no", name="uk_admin_batch_jobs_no"),
    )
    op.create_index(
        "idx_admin_batch_jobs_requester",
        "admin_batch_jobs",
        ["requested_by", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_admin_batch_jobs_scope",
        "admin_batch_jobs",
        ["scope_type", "scope_id", "job_type", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_admin_batch_jobs_status",
        "admin_batch_jobs",
        ["job_status", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "product_attributes",
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("attribute_code", sa.String(length=64), nullable=False),
        sa.Column("attribute_name", sa.String(length=128), nullable=False),
        sa.Column("value_text", sa.String(length=1000), nullable=False),
        sa.Column("value_normalized", sa.String(length=500), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("is_searchable", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_attributes_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_attributes")),
        sa.UniqueConstraint("product_id", "attribute_code", name="uk_product_attributes_code"),
    )
    op.create_table(
        "product_content_versions",
        sa.Column("content_version_no", sa.String(length=40), nullable=False),
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("content_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("source_content", mysql.MEDIUMTEXT(), nullable=False),
        sa.Column("source_hash", sa.BINARY(length=32), nullable=False),
        sa.Column("public_content_format", sa.String(length=24), nullable=False),
        sa.Column("safe_blocks", sa.JSON(), nullable=True),
        sa.Column("safe_html", mysql.MEDIUMTEXT(), nullable=True),
        sa.Column("safe_text", mysql.MEDIUMTEXT(), nullable=False),
        sa.Column("content_hash", sa.BINARY(length=32), nullable=False),
        sa.Column("sanitizer_policy_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("content_schema_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("security_scan_status", sa.String(length=16), nullable=False),
        sa.Column("version_status", sa.String(length=16), nullable=False),
        sa.Column("created_by", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("approved_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "((public_content_format = 'structured_v1' AND safe_blocks IS NOT NULL "
            "AND safe_html IS NULL) OR (public_content_format = 'safe_html_v1' "
            "AND safe_blocks IS NULL AND safe_html IS NOT NULL))",
            name=op.f("ck_product_content_versions_product_content_public_payload"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_product_content_versions_approved_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_product_content_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_content_versions_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_content_versions")),
        sa.UniqueConstraint("content_version_no", name="uk_product_content_versions_no"),
        sa.UniqueConstraint(
            "product_id", "content_version", name="uk_product_content_versions_product_version"
        ),
    )
    op.create_table(
        "product_faqs",
        sa.Column("faq_no", sa.String(length=40), nullable=False),
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("question", sa.String(length=1000), nullable=False),
        sa.Column("current_content_version_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("published_content_version_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("faq_status", sa.String(length=16), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["current_content_version_id"],
            ["product_faq_versions.id"],
            name="fk_product_faqs_current_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_faqs_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["published_content_version_id"],
            ["product_faq_versions.id"],
            name="fk_product_faqs_published_version",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_faqs")),
        sa.UniqueConstraint("faq_no", name="uk_product_faqs_no"),
    )
    op.create_index(
        "idx_product_faqs_product_status",
        "product_faqs",
        ["product_id", "faq_status", "sort_order"],
        unique=False,
    )
    op.create_table(
        "product_favorites",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("favorited_at", sa.DateTime(), nullable=False),
        sa.Column(
            "active_user_id",
            mysql.BIGINT(unsigned=True),
            sa.Computed(
                "CASE WHEN deleted_at IS NULL THEN user_id ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_favorites_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_product_favorites_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_favorites")),
        sa.UniqueConstraint(
            "product_id", "active_user_id", name="uk_product_favorites_active_user"
        ),
    )
    op.create_index(
        "idx_product_favorites_user",
        "product_favorites",
        ["user_id", "deleted_at", "favorited_at"],
        unique=False,
    )
    op.create_table(
        "product_fulfillment_profiles",
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("shipping_template_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("origin_region_code", sa.String(length=32), nullable=False),
        sa.Column("dispatch_min_hours", sa.SmallInteger(), nullable=False),
        sa.Column("dispatch_max_hours", sa.SmallInteger(), nullable=False),
        sa.Column("purchase_notice", sa.String(length=3000), nullable=True),
        sa.Column(
            "profile_version", mysql.INTEGER(unsigned=True), server_default="1", nullable=False
        ),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "dispatch_min_hours <= dispatch_max_hours",
            name=op.f("ck_product_fulfillment_profiles_product_dispatch_range"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_fulfillment_profiles_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["shipping_template_id"],
            ["shipping_templates.id"],
            name=op.f("fk_product_fulfillment_profiles_shipping_template_id_shipping_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_fulfillment_profiles")),
        sa.UniqueConstraint("product_id", name="uk_product_fulfillment_product"),
    )
    op.create_table(
        "product_skus",
        sa.Column("sku_no", sa.String(length=40), nullable=False),
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("merchant_sku_code", sa.String(length=64), nullable=True),
        sa.Column(
            "active_merchant_sku_code",
            sa.String(length=64),
            sa.Computed(
                "CASE WHEN sku_status = 'active' THEN merchant_sku_code ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("sku_name", sa.String(length=255), nullable=False),
        sa.Column("spec_values", sa.JSON(), nullable=False),
        sa.Column("spec_signature", sa.BINARY(length=32), nullable=False),
        sa.Column("sale_price_amount", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("market_price_amount", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("weight_grams", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("sku_status", sa.String(length=16), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "market_price_amount >= sale_price_amount",
            name=op.f("ck_product_skus_sku_market_price"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_skus_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_product_skus_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_skus")),
        sa.UniqueConstraint("product_id", "spec_signature", name="uk_product_skus_spec_signature"),
        sa.UniqueConstraint("sku_no", name="uk_product_skus_no"),
        sa.UniqueConstraint(
            "store_id", "active_merchant_sku_code", name="uk_product_skus_store_merchant_code"
        ),
    )
    op.create_index(
        "idx_skus_product_status", "product_skus", ["product_id", "sku_status", "id"], unique=False
    )
    op.create_table(
        "product_status_logs",
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("product_version", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_product_status_logs_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_status_logs_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_status_logs")),
    )
    op.create_index(
        "idx_product_status_logs_product",
        "product_status_logs",
        ["product_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "shipping_template_rules",
        sa.Column("shipping_template_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("region_scope", sa.JSON(), nullable=False),
        sa.Column("first_unit", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("additional_unit", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("first_fee_amount", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("additional_fee_amount", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("estimated_min_days", sa.SmallInteger(), nullable=True),
        sa.Column("estimated_max_days", sa.SmallInteger(), nullable=True),
        sa.Column("rule_status", sa.String(length=16), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "estimated_min_days IS NULL OR estimated_min_days <= estimated_max_days",
            name=op.f("ck_shipping_template_rules_shipping_estimate_range"),
        ),
        sa.ForeignKeyConstraint(
            ["shipping_template_id"],
            ["shipping_templates.id"],
            name=op.f("fk_shipping_template_rules_shipping_template_id_shipping_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipping_template_rules")),
    )
    op.create_index(
        "idx_shipping_rules_template",
        "shipping_template_rules",
        ["shipping_template_id", "rule_status", "id"],
        unique=False,
    )
    op.create_table(
        "store_certification_events",
        sa.Column("event_no", sa.String(length=40), nullable=False),
        sa.Column("certification_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("material_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("evidence_file_ids", sa.JSON(), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("required_materials", sa.JSON(), nullable=True),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("certification_version", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_store_certification_events_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["certification_id"],
            ["store_certifications.id"],
            name=op.f("fk_store_certification_events_certification_id_store_certifications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_certification_events")),
        sa.UniqueConstraint(
            "certification_id",
            "material_version",
            "event_type",
            name="uk_store_cert_event_material_type",
        ),
        sa.UniqueConstraint("event_no", name="uk_store_certification_events_no"),
    )
    op.create_index(
        "idx_store_cert_events_cert",
        "store_certification_events",
        ["certification_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "store_featured_products",
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("slot_type", sa.String(length=16), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_store_featured_products_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_featured_products_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_featured_products")),
        sa.UniqueConstraint(
            "store_id", "product_id", "slot_type", name="uk_store_featured_product_slot"
        ),
    )
    op.create_index(
        "idx_store_featured_active",
        "store_featured_products",
        ["store_id", "slot_type", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_table(
        "store_product_group_items",
        sa.Column("store_product_group_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_store_product_group_items_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_store_product_group_items_store_id_stores")
        ),
        sa.ForeignKeyConstraint(
            ["store_product_group_id"],
            ["store_product_groups.id"],
            name=op.f("fk_store_product_group_items_store_product_group_id_store_product_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_product_group_items")),
        sa.UniqueConstraint(
            "store_product_group_id", "product_id", name="uk_store_group_items_product"
        ),
    )
    op.create_index(
        "idx_store_group_items_order",
        "store_product_group_items",
        ["store_product_group_id", "sort_order", "id"],
        unique=False,
    )
    op.create_table(
        "admin_batch_job_items",
        sa.Column("job_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("item_key", sa.String(length=128), nullable=False),
        sa.Column("item_status", sa.String(length=16), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_no", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("input_hash", sa.BINARY(length=32), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["admin_batch_jobs.id"],
            name=op.f("fk_admin_batch_job_items_job_id_admin_batch_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_batch_job_items")),
        sa.UniqueConstraint("job_id", "item_key", name="uk_admin_batch_job_items_key"),
    )
    op.create_index(
        "idx_batch_job_items_status",
        "admin_batch_job_items",
        ["job_id", "item_status", "id"],
        unique=False,
    )
    op.create_table(
        "inventories",
        sa.Column("sku_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column(
            "on_hand_quantity", mysql.INTEGER(unsigned=True), server_default="0", nullable=False
        ),
        sa.Column(
            "reserved_quantity", mysql.INTEGER(unsigned=True), server_default="0", nullable=False
        ),
        sa.Column(
            "safety_stock_quantity",
            mysql.INTEGER(unsigned=True),
            server_default="0",
            nullable=False,
        ),
        sa.Column("sold_quantity", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.Column("inventory_status", sa.String(length=16), nullable=False),
        sa.Column("last_reconciled_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "reserved_quantity <= on_hand_quantity",
            name=op.f("ck_inventories_inventory_reserved_on_hand"),
        ),
        sa.CheckConstraint(
            "safety_stock_quantity <= on_hand_quantity",
            name=op.f("ck_inventories_inventory_safety_on_hand"),
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["product_skus.id"], name=op.f("fk_inventories_sku_id_product_skus")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventories")),
        sa.UniqueConstraint("sku_id", name="uk_inventories_sku"),
    )
    op.create_index(
        "idx_inventories_status",
        "inventories",
        ["inventory_status", "updated_at", "id"],
        unique=False,
    )
    op.create_table(
        "product_faq_versions",
        sa.Column("faq_version_no", sa.String(length=40), nullable=False),
        sa.Column("product_faq_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("content_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("source_content", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.BINARY(length=32), nullable=False),
        sa.Column("public_content_format", sa.String(length=24), nullable=False),
        sa.Column("safe_blocks", sa.JSON(), nullable=True),
        sa.Column("safe_html", sa.Text(), nullable=True),
        sa.Column("safe_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.BINARY(length=32), nullable=False),
        sa.Column("sanitizer_policy_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("content_schema_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("security_scan_status", sa.String(length=16), nullable=False),
        sa.Column("version_status", sa.String(length=16), nullable=False),
        sa.Column("created_by", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("approved_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "((public_content_format = 'structured_v1' AND safe_blocks IS NOT NULL "
            "AND safe_html IS NULL) OR (public_content_format = 'safe_html_v1' "
            "AND safe_blocks IS NULL AND safe_html IS NOT NULL))",
            name=op.f("ck_product_faq_versions_product_faq_public_payload"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_product_faq_versions_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_product_faq_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["product_faq_id"],
            ["product_faqs.id"],
            name=op.f("fk_product_faq_versions_product_faq_id_product_faqs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_faq_versions")),
        sa.UniqueConstraint("faq_version_no", name="uk_product_faq_versions_no"),
        sa.UniqueConstraint(
            "product_faq_id", "content_version", name="uk_product_faq_versions_faq_version"
        ),
    )
    op.create_table(
        "product_images",
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("sku_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("file_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("image_type", sa.String(length=16), nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("width", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("height", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("sort_order", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("image_status", sa.String(length=16), nullable=False),
        sa.Column(
            "active_product_main_scope",
            mysql.BIGINT(unsigned=True),
            sa.Computed(
                "CASE WHEN sku_id IS NULL AND image_type = 'main' "
                "AND image_status = 'active' THEN product_id ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["file_objects.id"], name=op.f("fk_product_images_file_id_file_objects")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_images_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["product_skus.id"], name=op.f("fk_product_images_sku_id_product_skus")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
        sa.UniqueConstraint("active_product_main_scope", name="uk_product_images_active_spu_main"),
        sa.UniqueConstraint("product_id", "sku_id", "sort_order", name="uk_product_images_order"),
    )
    op.create_index(
        "idx_product_images_product_sort",
        "product_images",
        ["product_id", "sku_id", "image_type", "sort_order", "id"],
        unique=False,
    )
    op.create_table(
        "inventory_logs",
        sa.Column("inventory_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("sku_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("operation_type", sa.String(length=32), nullable=False),
        sa.Column("on_hand_delta", sa.Integer(), nullable=False),
        sa.Column("reserved_delta", sa.Integer(), nullable=False),
        sa.Column("on_hand_before", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("on_hand_after", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("reserved_before", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("reserved_after", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("reference_type", sa.String(length=32), nullable=False),
        sa.Column("reference_no", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("inventory_version", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.CheckConstraint(
            "on_hand_after >= 0", name=op.f("ck_inventory_logs_inventory_log_on_hand_nonnegative")
        ),
        sa.CheckConstraint(
            "reserved_after >= 0", name=op.f("ck_inventory_logs_inventory_log_reserved_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_inventory_logs_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["inventories.id"],
            name=op.f("fk_inventory_logs_inventory_id_inventories"),
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["product_skus.id"], name=op.f("fk_inventory_logs_sku_id_product_skus")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_logs")),
        sa.UniqueConstraint("idempotency_key", name="uk_inventory_logs_idempotency"),
    )
    op.create_index(
        "idx_inventory_logs_reference",
        "inventory_logs",
        ["reference_type", "reference_no"],
        unique=False,
    )
    op.create_index(
        "idx_inventory_logs_sku_time",
        "inventory_logs",
        ["sku_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "inventory_reservations",
        sa.Column("reservation_no", sa.String(length=40), nullable=False),
        sa.Column("inventory_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("sku_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("order_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("order_item_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("quantity", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("reservation_status", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.Column("release_reason", sa.String(length=64), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_inventory_reservations_inventory_reservation_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["inventories.id"],
            name=op.f("fk_inventory_reservations_inventory_id_inventories"),
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["product_skus.id"],
            name=op.f("fk_inventory_reservations_sku_id_product_skus"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reservations")),
        sa.UniqueConstraint("idempotency_key", name="uk_inventory_reservations_idempotency"),
        sa.UniqueConstraint("order_item_id", name="uk_inventory_reservations_order_item"),
        sa.UniqueConstraint("reservation_no", name="uk_inventory_reservations_no"),
    )
    op.create_index(
        "idx_inventory_reservations_expiry",
        "inventory_reservations",
        ["reservation_status", "expires_at", "id"],
        unique=False,
    )
    # The following ownership pointers form intentional cycles. They are added
    # only after both sides exist so a clean MySQL database can enforce them.
    op.create_foreign_key(
        "fk_products_current_content_version",
        "products",
        "product_content_versions",
        ["current_detail_content_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_products_published_content_version",
        "products",
        "product_content_versions",
        ["published_detail_content_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_products_default_sku",
        "products",
        "product_skus",
        ["default_sku_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_product_faqs_current_version",
        "product_faqs",
        "product_faq_versions",
        ["current_content_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_product_faqs_published_version",
        "product_faqs",
        "product_faq_versions",
        ["published_content_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL may use an explicit composite index to back a foreign key. Dropping
    # those indexes individually before their tables fails with error 1553, so
    # the table drops below intentionally own index cleanup.
    op.drop_constraint(
        "fk_products_current_content_version",
        "products",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_products_published_content_version",
        "products",
        type_="foreignkey",
    )
    op.drop_constraint("fk_products_default_sku", "products", type_="foreignkey")
    op.drop_constraint(
        "fk_product_faqs_current_version",
        "product_faqs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_product_faqs_published_version",
        "product_faqs",
        type_="foreignkey",
    )

    op.drop_table("inventory_reservations")
    op.drop_table("inventory_logs")
    op.drop_table("product_images")
    op.drop_table("inventories")
    op.drop_table("admin_batch_job_items")
    op.drop_table("store_product_group_items")
    op.drop_table("store_featured_products")
    op.drop_table("store_certification_events")
    op.drop_table("shipping_template_rules")
    op.drop_table("product_status_logs")
    op.drop_table("product_fulfillment_profiles")
    op.drop_table("product_favorites")
    op.drop_table("product_attributes")
    op.drop_table("product_faq_versions")
    op.drop_table("product_faqs")
    op.drop_table("product_content_versions")
    op.drop_table("product_skus")
    op.drop_table("products")
    op.drop_table("admin_batch_jobs")
    op.drop_table("store_service_policies")
    op.drop_table("store_product_groups")
    op.drop_table("store_follows")
    op.drop_table("store_certifications")
    op.drop_table("store_categories")
    op.drop_table("store_announcements")
    op.drop_table("shipping_templates")
    op.drop_table("file_objects")
    op.drop_table("stores")
    op.drop_table("file_upload_sessions")
    op.drop_table("categories")
    op.drop_table("brands")
