"""add identity authentication and rbac foundation

Revision ID: 4d2275bed978
Revises:
Create Date: 2026-08-23 01:15:41.441141
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "4d2275bed978"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("scope_key", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_no", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("scope_key", "idempotency_key", name="uk_idempotency_scope_key"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_no", sa.String(length=40), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_no", sa.String(length=64), nullable=False),
        sa.Column("aggregate_version", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("event_status", sa.String(length=16), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("event_no", name="uk_outbox_events_no"),
    )
    op.create_index(
        "idx_outbox_events_aggregate",
        "outbox_events",
        ["aggregate_type", "aggregate_no", "id"],
        unique=False,
    )
    op.create_index(
        "idx_outbox_events_delivery",
        "outbox_events",
        ["event_status", "available_at", "id"],
        unique=False,
    )
    op.create_table(
        "permissions",
        sa.Column("permission_code", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("allowed_scope_types", sa.JSON(), nullable=False),
        sa.Column("delegation_policy", sa.String(length=32), nullable=False),
        sa.Column("requires_mfa", sa.Boolean(), nullable=False),
        sa.Column("requires_recent_auth", sa.Boolean(), nullable=False),
        sa.Column("approval_policy", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("permission_status", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("permission_code", name=op.f("uq_permissions_permission_code")),
    )
    op.create_table(
        "platform_content_entries",
        sa.Column("content_no", sa.String(length=40), nullable=False),
        sa.Column("content_key", sa.String(length=128), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("content_status", sa.String(length=16), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_content_entries")),
        sa.UniqueConstraint("content_key", name="uk_content_entries_key"),
        sa.UniqueConstraint("content_no", name=op.f("uq_platform_content_entries_content_no")),
    )
    op.create_table(
        "roles",
        sa.Column("role_no", sa.String(length=40), nullable=False),
        sa.Column("role_code", sa.String(length=64), nullable=False),
        sa.Column("role_name", sa.String(length=64), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("role_type", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("role_status", sa.String(length=16), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("role_no", name="uk_roles_no"),
        sa.UniqueConstraint("scope_type", "role_code", name="uk_roles_scope_code"),
    )
    op.create_table(
        "users",
        sa.Column("user_no", sa.String(length=40), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("username_normalized", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("avatar_object_key", sa.String(length=512), nullable=True),
        sa.Column("user_status", sa.String(length=32), nullable=False),
        sa.Column("status_reason_code", sa.String(length=64), nullable=True),
        sa.Column("status_expires_at", sa.DateTime(), nullable=True),
        sa.Column("current_status_record_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "permission_version", mysql.BIGINT(unsigned=True), server_default="1", nullable=False
        ),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("user_no", name="uk_users_user_no"),
        sa.UniqueConstraint("username_normalized", name="uk_users_username_normalized"),
    )
    op.create_index(
        "idx_users_status_created_at", "users", ["user_status", "created_at", "id"], unique=False
    )
    op.create_index(
        "idx_users_status_expiry", "users", ["user_status", "status_expires_at", "id"], unique=False
    )
    op.create_table(
        "admin_approval_requests",
        sa.Column("approval_request_no", sa.String(length=40), nullable=False),
        sa.Column("approval_type", sa.String(length=32), nullable=False),
        sa.Column("action_code", sa.String(length=64), nullable=False),
        sa.Column("initiator_user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("scope_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("required_permission_code", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_no", sa.String(length=64), nullable=False),
        sa.Column("command_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("command_payload_ciphertext", mysql.MEDIUMBLOB(), nullable=False),
        sa.Column("command_arguments_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("display_snapshot", sa.JSON(), nullable=False),
        sa.Column("resource_versions", sa.JSON(), nullable=False),
        sa.Column("approval_policy_snapshot", sa.JSON(), nullable=False),
        sa.Column("required_approval_count", sa.SmallInteger(), nullable=False),
        sa.Column("approved_count", sa.SmallInteger(), nullable=False),
        sa.Column("request_status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("execution_no", sa.String(length=40), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("execution_started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("result_resource_type", sa.String(length=64), nullable=True),
        sa.Column("result_resource_no", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["initiator_user_id"],
            ["users.id"],
            name=op.f("fk_admin_approval_requests_initiator_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_approval_requests")),
        sa.UniqueConstraint("approval_request_no", name="uk_admin_approval_request_no"),
        sa.UniqueConstraint(
            "initiator_user_id",
            "action_code",
            "idempotency_key",
            name="uk_admin_approval_idempotency",
        ),
    )
    op.create_index(
        "idx_admin_approvals_scope",
        "admin_approval_requests",
        ["scope_type", "scope_id", "request_status", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_admin_approvals_status_expiry",
        "admin_approval_requests",
        ["request_status", "expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_admin_approvals_target",
        "admin_approval_requests",
        ["target_type", "target_no", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "admin_mfa_authenticators",
        sa.Column("authenticator_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("authenticator_type", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("credential_id_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("public_key", mysql.VARBINARY(length=2048), nullable=True),
        sa.Column("sign_count", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("secret_ciphertext", mysql.VARBINARY(length=1024), nullable=True),
        sa.Column("recovery_codes_hashes", sa.JSON(), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=True),
        sa.Column("authenticator_status", sa.String(length=16), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_admin_mfa_authenticators_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_mfa_authenticators")),
        sa.UniqueConstraint(
            "authenticator_no", name=op.f("uq_admin_mfa_authenticators_authenticator_no")
        ),
        sa.UniqueConstraint(
            "credential_id_hash", name=op.f("uq_admin_mfa_authenticators_credential_id_hash")
        ),
    )
    op.create_table(
        "admin_operation_logs",
        sa.Column("operation_no", sa.String(length=40), nullable=False),
        sa.Column("operator_user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("scope_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("permission_code", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_no", sa.String(length=64), nullable=False),
        sa.Column("before_snapshot", sa.JSON(), nullable=True),
        sa.Column("after_snapshot", sa.JSON(), nullable=True),
        sa.Column("result_status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("ip_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["operator_user_id"],
            ["users.id"],
            name=op.f("fk_admin_operation_logs_operator_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_operation_logs")),
        sa.UniqueConstraint("operation_no", name=op.f("uq_admin_operation_logs_operation_no")),
    )
    op.create_index(
        "idx_admin_logs_operator_time",
        "admin_operation_logs",
        ["operator_user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_admin_logs_target",
        "admin_operation_logs",
        ["target_type", "target_no", "created_at"],
        unique=False,
    )
    op.create_table(
        "auth_sessions",
        sa.Column("session_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("refresh_token_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("token_family_no", sa.String(length=40), nullable=False),
        sa.Column("parent_session_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("device_no", sa.String(length=128), nullable=True),
        sa.Column("device_name", sa.String(length=128), nullable=True),
        sa.Column("client_type", sa.String(length=32), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("csrf_token_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("ip_ciphertext", mysql.VARBINARY(length=256), nullable=True),
        sa.Column("user_agent_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("authenticated_at", sa.DateTime(), nullable=False),
        sa.Column("authentication_methods", sa.JSON(), nullable=False),
        sa.Column("assurance_level", sa.String(length=16), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoke_reason", sa.String(length=64), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_auth_sessions_parent_session_id_auth_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("refresh_token_hash", name="uk_auth_sessions_refresh_token_hash"),
        sa.UniqueConstraint("session_no", name="uk_auth_sessions_session_no"),
    )
    op.create_index("idx_auth_sessions_family", "auth_sessions", ["token_family_no"], unique=False)
    op.create_index(
        "idx_auth_sessions_user_expires", "auth_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("conversation_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("store_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("conversation_type", sa.String(length=16), nullable=False),
        sa.Column("is_fixed", sa.Boolean(), nullable=False),
        sa.Column(
            "exclusive_user_key",
            mysql.BIGINT(unsigned=True),
            sa.Computed(
                "CASE WHEN conversation_type = 'exclusive' AND deleted_at IS NULL THEN user_id ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("conversation_status", sa.String(length=16), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_conversations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("conversation_no", name="uk_conversations_no"),
        sa.UniqueConstraint("exclusive_user_key", name="uk_conversations_exclusive_user"),
    )
    op.create_index(
        "idx_conversations_user_updated",
        "conversations",
        ["user_id", "updated_at", "id"],
        unique=False,
    )
    op.create_table(
        "platform_content_versions",
        sa.Column("content_version_no", sa.String(length=40), nullable=False),
        sa.Column("entry_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("document_version", sa.String(length=40), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("region_code", sa.String(length=16), nullable=False),
        sa.Column("safe_content", sa.Text(), nullable=False),
        sa.Column("content_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("publish_status", sa.String(length=16), nullable=False),
        sa.Column("effective_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["platform_content_entries.id"],
            name=op.f("fk_platform_content_versions_entry_id_platform_content_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_content_versions")),
        sa.UniqueConstraint(
            "content_version_no", name=op.f("uq_platform_content_versions_content_version_no")
        ),
        sa.UniqueConstraint(
            "entry_id", "document_version", name="uk_content_version_entry_version"
        ),
    )
    op.create_index(
        "idx_content_version_published",
        "platform_content_versions",
        ["entry_id", "locale", "region_code", "publish_status", "effective_at"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("permission_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("condition_config", sa.JSON(), nullable=True),
        sa.Column("granted_by", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_role_permissions_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint("role_id", "permission_id", name="uk_role_permissions_pair"),
    )
    op.create_table(
        "user_addresses",
        sa.Column("address_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("recipient_name_ciphertext", mysql.VARBINARY(length=512), nullable=False),
        sa.Column("phone_ciphertext", mysql.VARBINARY(length=512), nullable=False),
        sa.Column("phone_last4", sa.String(length=4), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("province_code", sa.String(length=32), nullable=False),
        sa.Column("city_code", sa.String(length=32), nullable=False),
        sa.Column("district_code", sa.String(length=32), nullable=False),
        sa.Column("address_ciphertext", mysql.VARBINARY(length=2048), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=True),
        sa.Column("label", sa.String(length=32), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "active_default_user_id",
            mysql.BIGINT(unsigned=True),
            sa.Computed(
                "CASE WHEN is_default = 1 AND deleted_at IS NULL THEN user_id ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_addresses_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_addresses")),
        sa.UniqueConstraint("active_default_user_id", name="uk_user_addresses_active_default"),
        sa.UniqueConstraint("address_no", name="uk_user_addresses_no"),
    )
    op.create_index(
        "idx_user_addresses_user", "user_addresses", ["user_id", "deleted_at", "id"], unique=False
    )
    op.create_table(
        "user_credentials",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("credential_type", sa.String(length=32), nullable=False),
        sa.Column("identifier_ciphertext", mysql.VARBINARY(length=512), nullable=True),
        sa.Column("identifier_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column(
            "active_identifier_hash",
            mysql.BINARY(length=32),
            sa.Computed(
                "CASE WHEN credential_status = 'active' THEN identifier_hash ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.Column("secret_hash", mysql.VARBINARY(length=512), nullable=True),
        sa.Column("algorithm", sa.String(length=32), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("failed_attempts", sa.SmallInteger(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column(
            "credential_version", mysql.BIGINT(unsigned=True), server_default="1", nullable=False
        ),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(), nullable=True),
        sa.Column("credential_status", sa.String(length=32), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_credentials_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_credentials")),
        sa.UniqueConstraint(
            "credential_type", "active_identifier_hash", name="uk_credentials_active_identifier"
        ),
        sa.UniqueConstraint("user_id", "credential_type", name="uk_user_credentials_user_type"),
    )
    op.create_index(
        "idx_credentials_identifier",
        "user_credentials",
        ["credential_type", "identifier_hash"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("role_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("grant_no", sa.String(length=40), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("scope_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("grant_status", sa.String(length=16), nullable=False),
        sa.Column("active_grant_key", mysql.BINARY(length=32), nullable=True),
        sa.Column("granted_by", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("grant_reason", sa.String(length=500), nullable=False),
        sa.Column("revoke_reason", sa.String(length=500), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_user_roles_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"], ["users.id"], name=op.f("fk_user_roles_revoked_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("active_grant_key", name="uk_user_roles_active_grant"),
        sa.UniqueConstraint("grant_no", name="uk_user_roles_grant_no"),
    )
    op.create_index(
        "idx_user_roles_expiry", "user_roles", ["grant_status", "expires_at", "id"], unique=False
    )
    op.create_index(
        "idx_user_roles_scope",
        "user_roles",
        ["scope_type", "scope_id", "role_id", "grant_status"],
        unique=False,
    )
    op.create_table(
        "user_status_records",
        sa.Column("status_record_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=False),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("effective_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("scope_type", sa.String(length=16), nullable=True),
        sa.Column("scope_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("expected_user_version", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("result_user_version", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("idempotency_scope_key", mysql.BINARY(length=32), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_user_status_records_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_status_records_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_status_records")),
        sa.UniqueConstraint("idempotency_scope_key", name="uk_user_status_idempotency"),
        sa.UniqueConstraint("status_record_no", name="uk_user_status_record_no"),
    )
    op.create_index(
        "idx_user_status_records_expiry",
        "user_status_records",
        ["to_status", "expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_user_status_records_user",
        "user_status_records",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_users_current_status_record_id_user_status_records",
        "users",
        "user_status_records",
        ["current_status_record_id"],
        ["id"],
    )
    op.create_table(
        "verification_codes",
        sa.Column("verification_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("code_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), nullable=False),
        sa.Column("send_channel", sa.String(length=32), nullable=False),
        sa.Column("delivery_status", sa.String(length=16), nullable=False),
        sa.Column("provider_reference_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(), nullable=True),
        sa.Column("request_ip_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_verification_codes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_codes")),
        sa.UniqueConstraint("verification_no", name="uk_verification_codes_no"),
    )
    op.create_index("idx_verification_expires", "verification_codes", ["expires_at"], unique=False)
    op.create_index(
        "idx_verification_target_purpose",
        "verification_codes",
        ["target_hash", "purpose", "created_at"],
        unique=False,
    )
    op.create_table(
        "admin_approval_decisions",
        sa.Column("decision_no", sa.String(length=40), nullable=False),
        sa.Column("approval_request_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("approver_user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("permission_code_snapshot", sa.String(length=128), nullable=False),
        sa.Column("scope_snapshot", sa.JSON(), nullable=False),
        sa.Column("assurance_level", sa.String(length=16), nullable=False),
        sa.Column("authenticated_at", sa.DateTime(), nullable=False),
        sa.Column("decision_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["admin_approval_requests.id"],
            name=op.f("fk_admin_approval_decisions_approval_request_id_admin_approval_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["approver_user_id"],
            ["users.id"],
            name=op.f("fk_admin_approval_decisions_approver_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_approval_decisions")),
        sa.UniqueConstraint(
            "approval_request_id", "approver_user_id", name="uk_admin_approval_decision_approver"
        ),
        sa.UniqueConstraint("decision_no", name=op.f("uq_admin_approval_decisions_decision_no")),
    )
    op.create_table(
        "admin_approval_events",
        sa.Column("event_no", sa.String(length=40), nullable=False),
        sa.Column("approval_request_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("snapshot_redacted", sa.JSON(), nullable=True),
        sa.Column("request_version", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["admin_approval_requests.id"],
            name=op.f("fk_admin_approval_events_approval_request_id_admin_approval_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_approval_events")),
        sa.UniqueConstraint("event_no", name=op.f("uq_admin_approval_events_event_no")),
    )
    op.create_index(
        "idx_admin_approval_events_request",
        "admin_approval_events",
        ["approval_request_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "admin_sensitive_access_grants",
        sa.Column("grant_no", sa.String(length=40), nullable=False),
        sa.Column("admin_user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("auth_session_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_no", sa.String(length=64), nullable=False),
        sa.Column("field_set", sa.JSON(), nullable=False),
        sa.Column("purpose_code", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("grant_status", sa.String(length=16), nullable=False),
        sa.Column("assurance_level", sa.String(length=16), nullable=False),
        sa.Column("authenticated_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_by", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("revoke_reason", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["users.id"],
            name=op.f("fk_admin_sensitive_access_grants_admin_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["auth_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_admin_sensitive_access_grants_auth_session_id_auth_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
            name=op.f("fk_admin_sensitive_access_grants_revoked_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_sensitive_access_grants")),
        sa.UniqueConstraint("grant_no", name=op.f("uq_admin_sensitive_access_grants_grant_no")),
    )
    op.create_index(
        "idx_sensitive_grants_admin_session",
        "admin_sensitive_access_grants",
        ["admin_user_id", "auth_session_id", "grant_status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "idx_sensitive_grants_target",
        "admin_sensitive_access_grants",
        ["target_type", "target_no", "grant_status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "auth_attempts",
        sa.Column("attempt_no", sa.String(length=40), nullable=False),
        sa.Column("attempt_type", sa.String(length=24), nullable=False),
        sa.Column("auth_method", sa.String(length=24), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("identifier_monitoring_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("session_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("result", sa.String(length=24), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("risk_policy_version", sa.String(length=40), nullable=False),
        sa.Column("challenge_type", sa.String(length=32), nullable=True),
        sa.Column("ip_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("device_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("user_agent_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_auth_attempts_session_id_auth_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_attempts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_attempts")),
        sa.UniqueConstraint("attempt_no", name="uk_auth_attempt_no"),
    )
    op.create_index(
        "idx_auth_attempts_identifier_time",
        "auth_attempts",
        ["identifier_monitoring_hash", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_auth_attempts_ip_time", "auth_attempts", ["ip_hash", "occurred_at", "id"], unique=False
    )
    op.create_index(
        "idx_auth_attempts_result_time",
        "auth_attempts",
        ["result", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_auth_attempts_user_time",
        "auth_attempts",
        ["user_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_table(
        "conversation_status_logs",
        sa.Column("conversation_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_status_logs_conversation_id_conversations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_status_logs")),
    )
    op.create_table(
        "credential_change_records",
        sa.Column("change_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("credential_type", sa.String(length=16), nullable=False),
        sa.Column("old_credential_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("credential_version_before", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("new_identifier_ciphertext", mysql.VARBINARY(length=512), nullable=True),
        sa.Column("new_identifier_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("old_verification_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("new_verification_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("change_status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("request_ip_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.Column("version", mysql.BIGINT(unsigned=True), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["new_verification_id"],
            ["verification_codes.id"],
            name=op.f("fk_credential_change_records_new_verification_id_verification_codes"),
        ),
        sa.ForeignKeyConstraint(
            ["old_credential_id"],
            ["user_credentials.id"],
            name=op.f("fk_credential_change_records_old_credential_id_user_credentials"),
        ),
        sa.ForeignKeyConstraint(
            ["old_verification_id"],
            ["verification_codes.id"],
            name=op.f("fk_credential_change_records_old_verification_id_verification_codes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_credential_change_records_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credential_change_records")),
        sa.UniqueConstraint("change_no", name="uk_credential_change_no"),
    )
    op.create_index(
        "idx_credential_changes_user_status",
        "credential_change_records",
        ["user_id", "change_status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "password_reset_records",
        sa.Column("reset_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("verification_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("reset_token_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("credential_version_before", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(), nullable=True),
        sa.Column("request_ip_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_reset_records_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["verification_codes.id"],
            name=op.f("fk_password_reset_records_verification_id_verification_codes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_records")),
        sa.UniqueConstraint("reset_no", name="uk_password_reset_no"),
        sa.UniqueConstraint("reset_token_hash", name="uk_password_reset_token_hash"),
    )
    op.create_table(
        "user_agreement_acceptances",
        sa.Column("acceptance_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("content_entry_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("content_version_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("document_version", sa.String(length=40), nullable=False),
        sa.Column("content_hash", mysql.BINARY(length=32), nullable=False),
        sa.Column("acceptance_context", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("region_code", sa.String(length=16), nullable=False),
        sa.Column("ip_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("user_agent_hash", mysql.BINARY(length=32), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["content_entry_id"],
            ["platform_content_entries.id"],
            name=op.f("fk_user_agreement_acceptances_content_entry_id_platform_content_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["platform_content_versions.id"],
            name=op.f("fk_user_agreement_acceptances_content_version_id_platform_content_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_agreement_acceptances_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_agreement_acceptances")),
        sa.UniqueConstraint(
            "acceptance_no", name=op.f("uq_user_agreement_acceptances_acceptance_no")
        ),
        sa.UniqueConstraint(
            "user_id",
            "document_type",
            "content_version_id",
            "acceptance_context",
            name="uk_agreement_acceptance_fact",
        ),
    )
    op.create_index(
        "idx_agreement_acceptances_user_time",
        "user_agreement_acceptances",
        ["user_id", "accepted_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_agreement_acceptances_version",
        "user_agreement_acceptances",
        ["content_version_id", "accepted_at", "id"],
        unique=False,
    )
    op.create_table(
        "user_role_events",
        sa.Column("event_no", sa.String(length=40), nullable=False),
        sa.Column("grant_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("grant_snapshot", sa.JSON(), nullable=False),
        sa.Column("permission_version_after", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), "mysql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("utc_timestamp(6)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_user_role_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"], ["user_roles.id"], name=op.f("fk_user_role_events_grant_id_user_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role_events")),
        sa.UniqueConstraint("event_no", name=op.f("uq_user_role_events_event_no")),
    )
    op.create_index(
        "idx_user_role_events_grant",
        "user_role_events",
        ["grant_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "fk_users_current_status_record_id_user_status_records",
        "users",
        type_="foreignkey",
    )
    op.drop_table("user_role_events")
    op.drop_table("user_agreement_acceptances")
    op.drop_table("password_reset_records")
    op.drop_table("credential_change_records")
    op.drop_table("conversation_status_logs")
    op.drop_table("auth_attempts")
    op.drop_table("admin_sensitive_access_grants")
    op.drop_table("admin_approval_events")
    op.drop_table("admin_approval_decisions")
    op.drop_table("verification_codes")
    op.drop_table("user_status_records")
    op.drop_table("user_roles")
    op.drop_table("user_credentials")
    op.drop_table("user_addresses")
    op.drop_table("role_permissions")
    op.drop_table("platform_content_versions")
    op.drop_table("conversations")
    op.drop_table("auth_sessions")
    op.drop_table("admin_operation_logs")
    op.drop_table("admin_mfa_authenticators")
    op.drop_table("admin_approval_requests")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("platform_content_entries")
    op.drop_table("permissions")
    op.drop_table("outbox_events")
    op.drop_table("idempotency_records")
