<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { apiRequest, createIdempotencyKey, errorMessage } from '@/api/http'
import { useUserAuthStore } from '@/stores/user-auth'
interface Security { password_set: boolean; password_changed_at: string | null; bound_accounts: Array<{ type: string; masked: string }>; active_session_count: number }
interface Session { session_id: string; device_name: string | null; last_seen_at: string; expires_at: string; is_current: boolean }
const auth = useUserAuthStore(), security = ref<Security | null>(null), sessions = ref<Session[]>([]), error = ref(''), message = ref('')
const currentPassword = ref(''), newPassword = ref(''), contactType = ref<'email' | 'phone'>('email'), newTarget = ref(''), contactPassword = ref(''), changeTicket = ref(''), verificationId = ref(''), verificationCode = ref('')
async function load() { security.value = (await apiRequest<Security>('/users/me/security', {}, auth.accessToken)).data; sessions.value = (await apiRequest<Session[]>('/auth/sessions', {}, auth.accessToken)).data }
onMounted(() => load().catch((reason) => { error.value = errorMessage(reason) }))
async function changePassword() { error.value = ''; try { await apiRequest('/users/me/password', { method: 'PUT', headers: { 'Idempotency-Key': createIdempotencyKey('password-change') }, body: JSON.stringify({ current_password: currentPassword.value, new_password: newPassword.value }) }, auth.accessToken); currentPassword.value = ''; newPassword.value = ''; message.value = '密码已修改。'; await load() } catch (reason) { error.value = errorMessage(reason) } }
async function revoke(sessionId: string) { try { await apiRequest(`/auth/sessions/${sessionId}`, { method: 'DELETE' }, auth.accessToken); await load() } catch (reason) { error.value = errorMessage(reason) } }
async function beginContactChange() { try { const result = await apiRequest<{ change_ticket_id: string }>('/users/me/contact-change-tickets', { method: 'POST', headers: { 'Idempotency-Key': createIdempotencyKey('contact-ticket') }, body: JSON.stringify({ credential_type: contactType.value, current_password: contactPassword.value }) }, auth.accessToken); changeTicket.value = result.data.change_ticket_id; const sent = await apiRequest<{ verification_id: string }>('/auth/verification-codes', { method: 'POST', body: JSON.stringify({ purpose: `change_${contactType.value}`, target_type: contactType.value, target: newTarget.value, locale: 'zh-CN', challenge_token: null, change_ticket_id: changeTicket.value }) }, auth.accessToken); verificationId.value = sent.data.verification_id; message.value = '新联系方式验证码已发送。' } catch (reason) { error.value = errorMessage(reason) } }
async function finishContactChange() { try { await apiRequest('/users/me/contact-changes', { method: 'POST', headers: { 'Idempotency-Key': createIdempotencyKey('contact-change') }, body: JSON.stringify({ change_ticket_id: changeTicket.value, new_target: newTarget.value, verification_id: verificationId.value, verification_code: verificationCode.value }) }, auth.accessToken); changeTicket.value = ''; verificationId.value = ''; verificationCode.value = ''; message.value = '联系方式已更新。'; await load() } catch (reason) { error.value = errorMessage(reason) } }
</script>
<template><section class="settings-page"><p class="eyebrow">我的</p><h1>账号安全</h1><p v-if="message" class="alert success">{{ message }}</p><p v-if="error" class="alert error">{{ error }}</p>
  <div class="settings-grid"><form class="card" @submit.prevent="changePassword"><h2>修改密码</h2><label>当前密码<input v-model="currentPassword" autocomplete="current-password" type="password" required /></label><label>新密码<input v-model="newPassword" autocomplete="new-password" minlength="15" type="password" required /></label><button>修改密码</button></form>
  <form class="card" @submit.prevent="finishContactChange"><h2>更换联系方式</h2><label>类型<select v-model="contactType"><option value="email">邮箱</option><option value="phone">手机号</option></select></label><label>新联系方式<input v-model="newTarget" required /></label><label>当前密码<input v-model="contactPassword" type="password" required /></label><button class="secondary" type="button" @click="beginContactChange">验证并发送新验证码</button><label>新目标验证码<input v-model="verificationCode" maxlength="6" /></label><button :disabled="!verificationId">确认换绑</button></form></div>
  <article class="card"><div class="page-heading"><h2>登录设备（{{ security?.active_session_count ?? 0 }}）</h2></div><ul class="session-list"><li v-for="item in sessions" :key="item.session_id"><div><strong>{{ item.device_name || '未知设备' }}</strong><small>{{ item.is_current ? '当前会话' : `最近活动 ${item.last_seen_at}` }}</small></div><button v-if="!item.is_current" class="danger small" @click="revoke(item.session_id)">退出设备</button></li></ul></article>
</section></template>
