<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getAdminDeadLetter, ignoreAdminDeadLetter, previewAdminDeadLetterReplay, replayAdminDeadLetter, type DeadLetterEvent, type DeadLetterReplayPreview } from '@/api/admin-events'
import { errorMessage } from '@/api/http'
import { useAdminAuthStore } from '@/stores/admin-auth'
const route = useRoute(), router = useRouter(), auth = useAdminAuthStore(), item = ref<DeadLetterEvent | null>(null), preview = ref<DeadLetterReplayPreview | null>(null), etag = ref(''), error = ref(''), busy = ref(false), form = reactive({ reason_code: 'CONTROLLED_EVENT_REPLAY', reason: '' })
const canPreview = computed(() => auth.has('events:operate') && item.value?.available_actions.includes('preview_replay'))
const canIgnore = computed(() => auth.has('events:operate') && item.value?.available_actions.includes('ignore'))
function dateTime(value: string | null) { return value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—' }
async function load() { const response = await getAdminDeadLetter(String(route.params.deadLetterId), auth.accessToken!); item.value = response.data; etag.value = response.headers.get('etag') ?? ''; preview.value = null }
async function createPreview() { if (!item.value) return; busy.value = true; error.value = ''; try { const response = await previewAdminDeadLetterReplay(item.value.dead_letter_id, auth.accessToken!); preview.value = response.data; etag.value = response.headers.get('etag') ?? etag.value } catch (cause) { error.value = errorMessage(cause) } finally { busy.value = false } }
async function requestReplay() { if (!item.value || !preview.value || !form.reason.trim()) return; busy.value = true; error.value = ''; try { const response = await replayAdminDeadLetter(item.value.dead_letter_id, etag.value, preview.value.preview_token, form.reason_code, form.reason.trim(), auth.accessToken!); await router.push(`/admin/approval-requests/${response.data.approval_request_id}`) } catch (cause) { error.value = errorMessage(cause) } finally { busy.value = false } }
async function ignoreEvent() { if (!item.value || form.reason.trim().length < 5) return; busy.value = true; error.value = ''; try { const response = await ignoreAdminDeadLetter(item.value.dead_letter_id, etag.value, form.reason.trim(), auth.accessToken!); item.value = response.data; etag.value = response.headers.get('etag') ?? etag.value; preview.value = null } catch (cause) { error.value = errorMessage(cause) } finally { busy.value = false } }
onMounted(() => load().catch((cause) => { error.value = errorMessage(cause) }))
</script>
<template><section v-if="item" class="admin-page-stack"><header class="page-heading"><div><p class="eyebrow">死信 · {{ item.dead_letter_id }}</p><h1>{{ item.event_type }}</h1><p class="muted">{{ item.source_type }} · {{ item.source_id }} · {{ item.status }}</p></div></header><p v-if="error" class="alert error" role="alert">{{ error }}</p><div class="settings-grid"><article class="card"><h2>失败事实</h2><dl class="detail-list"><dt>错误码</dt><dd>{{ item.last_error_code }}</dd><dt>安全错误摘要</dt><dd>{{ item.last_error }}</dd><dt>失败次数</dt><dd>{{ item.failure_count }}</dd><dt>首次/最后失败</dt><dd>{{ dateTime(item.first_failed_at) }} / {{ dateTime(item.last_failed_at) }}</dd><dt>原 Trace</dt><dd>{{ item.original_trace_id || '—' }}</dd></dl></article><article class="card"><h2>不可变 Payload 摘要</h2><dl class="detail-list"><dt>Hash</dt><dd>{{ item.payload_hash }}</dd><dt>字段键</dt><dd>{{ item.payload_keys.join('、') || '无可展示字段' }}</dd><dt>Schema</dt><dd>v{{ item.schema_version }}</dd><dt>范围</dt><dd>{{ item.scope_type }}:{{ item.scope_id }}</dd><dt>版本</dt><dd>v{{ item.version }}</dd></dl><p>页面不返回、编辑或替换原 Payload 内容。</p></article></div><div v-if="canPreview || canIgnore" class="card admin-editor"><h2>处理方式</h2><p>确认消费者与资源状态后选择重放；历史测试、已撤销主体或不应再执行的事件可标记为忽略。两种操作都会记录管理员审计。</p><label>处理说明<textarea v-model.trim="form.reason" required minlength="5" maxlength="1000" placeholder="说明重放或忽略依据" /></label><div class="inline-actions"><button v-if="canPreview && !preview" :disabled="busy" @click="createPreview">生成重放影响预览</button><button v-if="canIgnore" type="button" class="danger" :disabled="busy || form.reason.trim().length < 5" @click="ignoreEvent">确认忽略此事件</button></div></div><article v-if="preview" class="card"><h2>重放影响预览</h2><p><strong>{{ preview.replayable ? '可以提交审批' : '当前不可重放' }}</strong> · 原事件状态 {{ preview.source_status || '不可用' }} · 预览有效至 {{ dateTime(preview.expires_at) }}</p><ul><li v-for="impact in preview.impact_summary" :key="impact">{{ impact }}</li></ul><p v-if="preview.blockers.length" class="alert error">阻断：{{ preview.blockers.join('、') }}</p><form v-if="preview.replayable" @submit.prevent="requestReplay"><p>需要 {{ preview.required_approval_count }} 名不同管理员批准，发起人不能自批。</p><label>原因码<input v-model.trim="form.reason_code" required pattern="[A-Z][A-Z0-9_]{1,63}" /></label><button :disabled="busy || !form.reason">提交双人复核</button></form></article></section><p v-else-if="!error">正在加载…</p><p v-else class="alert error" role="alert">{{ error }}</p></template>
