<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { bindAgentSkill, createAgentVersion, listAgents, listSkills, publishAgentVersion, type AgentSummary, type SkillSummary } from '@/api/admin-ai'
import { errorMessage } from '@/api/http'
import PageState from '@/components/PageState.vue'
import { confirmAction } from '@/composables/confirmation'
import { useAdminAuthStore } from '@/stores/admin-auth'
const auth = useAdminAuthStore(), items = ref<AgentSummary[]>([]), skills = ref<SkillSummary[]>([]), loading = ref(true), error = ref(''), notice = ref('')
const draft = reactive({ agent_id: '', system_prompt: '', model_profile: 'balanced', tool_allowlist: '[]', policy_config: '{\n  "evaluation_report": { "passed": false }\n}' })
const binding = reactive({ agent_id: '', agent_version_no: 1, skill_id: '', skill_version_no: 1 })
const token = () => auth.accessToken!
async function load() { loading.value = true; try { const [agents, skillList] = await Promise.all([listAgents(token()), listSkills(token())]); items.value = agents.data.items; skills.value = skillList.data.items } catch (cause) { error.value = errorMessage(cause) } finally { loading.value = false } }
async function createVersion() { try { await createAgentVersion(draft.agent_id, { system_prompt: draft.system_prompt, model_profile: draft.model_profile, tool_allowlist: JSON.parse(draft.tool_allowlist), policy_config: JSON.parse(draft.policy_config) }, token()); notice.value = 'Agent 草稿版本已创建。'; await load() } catch (cause) { error.value = cause instanceof SyntaxError ? 'Tool Allowlist 或 Policy 不是有效 JSON。' : errorMessage(cause) } }
async function bindSkill() { try { await bindAgentSkill(binding.agent_id, binding.agent_version_no, { skill_id: binding.skill_id, skill_version_no: binding.skill_version_no }, token()); notice.value = '已将固定 Skill Version 绑定到 Agent 草稿。'; await load() } catch (cause) { error.value = errorMessage(cause) } }
async function publish(agent: AgentSummary, version: number) { if (!await confirmAction('确认发起 Agent Version 双人发布审批吗？')) return; try { const result = (await publishAgentVersion(agent.agent_id, version, token())).data; notice.value = `审批 ${result.approval_request_id} 已创建。`; await load() } catch (cause) { error.value = errorMessage(cause) } }
onMounted(load)
</script>
<template><section class="admin-page-stack"><header class="page-heading"><div><p class="eyebrow">Agent Registry</p><h1>Agent 版本</h1><p class="muted">Prompt、模型档位、Tool Allowlist、Policy 与 Skill Binding 固定到不可变版本；发布必须经过评估和双人复核。</p></div></header><p v-if="error" class="alert error">{{ error }}</p><p v-if="notice" class="alert success">{{ notice }}</p><div class="admin-split"><PageState :loading="loading" :error="''" :empty="!loading && items.length === 0" empty-title="暂无 Agent"><div class="card-list"><article v-for="item in items" :key="item.agent_id" class="card"><div class="card-heading"><div><h2>{{ item.display_name }}</h2><p>{{ item.agent_code }} · {{ item.scope_type }}</p></div><span class="badge">{{ item.status }}</span></div><details v-for="version in item.versions" :key="version.version_no"><summary>Version {{ version.version_no }} · {{ version.status }} · {{ version.model_profile }}</summary><h3>System Prompt</h3><pre>{{ version.system_prompt }}</pre><h3>Tool Allowlist</h3><code>{{ version.tool_allowlist.join('\n') }}</code><h3>Policy</h3><pre>{{ JSON.stringify(version.policy_config, null, 2) }}</pre><button v-if="auth.has('ai_agents:publish') && version.status === 'draft'" @click="publish(item, version.version_no)">发起发布审批</button></details></article></div></PageState><div v-if="auth.has('ai_agents:manage')" class="card-list"><form class="card admin-editor" @submit.prevent="createVersion"><h2>新建 Agent 草稿版本</h2><label>Agent<select v-model="draft.agent_id" required><option value="">请选择</option><option v-for="item in items" :key="item.agent_id" :value="item.agent_id">{{ item.display_name }}</option></select></label><label>System Prompt<textarea v-model="draft.system_prompt" required></textarea></label><label>Model Profile<input v-model="draft.model_profile" required></label><label>Tool Allowlist JSON<textarea v-model="draft.tool_allowlist" required></textarea></label><label>Policy / Evaluation JSON<textarea v-model="draft.policy_config" required></textarea></label><button>创建草稿</button></form><form class="card admin-editor" @submit.prevent="bindSkill"><h2>绑定固定 Skill Version</h2><label>Agent<select v-model="binding.agent_id" required><option value="">请选择</option><option v-for="item in items" :key="item.agent_id" :value="item.agent_id">{{ item.display_name }}</option></select></label><label>Agent Version<input v-model.number="binding.agent_version_no" type="number" min="1" required></label><label>Skill<select v-model="binding.skill_id" required><option value="">请选择已发布 Skill</option><option v-for="item in skills" :key="item.skill_id" :value="item.skill_id">{{ item.display_name }}</option></select></label><label>Skill Version<input v-model.number="binding.skill_version_no" type="number" min="1" required></label><button>绑定</button></form></div></div></section></template>
