<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { createContent, getContent, publishContent, updateContent, withdrawContent, type PlatformContent } from '@/api/admin-content'
import { errorMessage } from '@/api/http'
import { confirmAction } from '@/composables/confirmation'
import { useAdminAuthStore } from '@/stores/admin-auth'
const auth = useAdminAuthStore(), route = useRoute(), router = useRouter(), item = ref<PlatformContent | null>(null), error = ref(''), notice = ref('')
const form = reactive({ content_key: '', content_type: 'announcement' as 'banner' | 'announcement' | 'help_article' | 'footer' | 'about', title: '', locale: 'zh-CN', region_code: 'CN', source_format: 'plain_text' as 'plain_text' | 'structured' | 'html', source_content: '' })
const id = () => typeof route.params.contentId === 'string' ? route.params.contentId : ''
function token() { if (!auth.accessToken) throw new Error('管理端登录已失效。'); return auth.accessToken }
async function load() { if (!id()) return; try { item.value = (await getContent(id(), token())).data; form.title = item.value.title; const latest = item.value.versions[0]; if (latest) { form.locale = latest.locale; form.region_code = latest.region_code; form.source_content = latest.text } } catch (cause) { error.value = errorMessage(cause) } }
async function save() { error.value = ''; try { if (!id()) { const result = await createContent(form, token()); await router.replace(`/admin/content/${result.data.content_id}`) } else if (item.value) { item.value = (await updateContent(id(), form, item.value.version, token())).data } notice.value = '内容草稿版本已保存。' } catch (cause) { error.value = errorMessage(cause) } }
async function publish(version: string) { if (!await confirmAction(`确认发布 ${version}？`)) return; try { item.value = (await publishContent(id(), version, token())).data; notice.value = '内容版本已发布。' } catch (cause) { error.value = errorMessage(cause) } }
async function withdraw() { if (!await confirmAction('确认撤回当前公开内容？', { tone: 'danger' })) return; try { item.value = (await withdrawContent(id(), token())).data; notice.value = '公开内容已撤回。' } catch (cause) { error.value = errorMessage(cause) } }
onMounted(load)
</script>
<template><section class="admin-page-stack"><header class="page-heading"><div><p class="eyebrow">版本化内容</p><h1>{{ id() ? '编辑平台内容' : '新建平台内容' }}</h1><p class="muted">HTML 会经过严格白名单净化；发布与撤回需要 MFA、近期认证及相应权限。</p></div></header><p v-if="error" class="alert error">{{ error }}</p><p v-if="notice" class="alert success">{{ notice }}</p><form class="card admin-editor" @submit.prevent="save"><label v-if="!id()">Content Key<input v-model="form.content_key" required pattern="[a-z][a-z0-9_.-]{2,127}"></label><label v-if="!id()">类型<select v-model="form.content_type"><option value="banner">Banner</option><option value="announcement">公告</option><option value="help_article">帮助</option><option value="footer">页脚</option><option value="about">关于</option></select></label><label>标题<input v-model="form.title" required maxlength="256"></label><div class="field-grid"><label>语言<input v-model="form.locale" required></label><label>地区<input v-model="form.region_code" required></label></div><label>源格式<select v-model="form.source_format"><option value="plain_text">纯文本</option><option value="structured">Structured JSON</option><option value="html">受限 HTML</option></select></label><label>内容<textarea v-model="form.source_content" required></textarea></label><button v-if="auth.has('content:manage')">保存为新草稿版本</button></form><div v-if="item" class="card-list"><article v-for="version in item.versions" :key="version.content_version_id" class="card"><div class="card-heading"><strong>{{ version.version }}</strong><span class="badge">{{ version.status }}</span></div><pre>{{ version.text }}</pre><button v-if="auth.has('content:publish') && version.status === 'draft'" @click="publish(version.version)">发布此版本</button></article><button v-if="auth.has('content:publish') && item.status === 'active'" class="danger" @click="withdraw">撤回公开内容</button></div></section></template>
