<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { apiRequest, createIdempotencyKey, errorMessage } from '@/api/http'
import { useAdminAuthStore } from '@/stores/admin-auth'
interface Approval { approval_request_id: string; approval_type: string; action_code: string; target_type: string; target_id: string; display_snapshot: Record<string, unknown>; resource_versions: Record<string, unknown>; approved_count: number; required_approval_count: number; status: string; expires_at: string; version: number }
const route = useRoute(), auth = useAdminAuthStore(), item = ref<Approval | null>(null), etag = ref(''), reason = ref(''), error = ref(''), message = ref('')
async function load() { const response = await apiRequest<Approval>(`/admin/approval-requests/${String(route.params.approvalRequestId)}`, {}, auth.accessToken); item.value = response.data; etag.value = response.headers.get('etag') ?? '' }
onMounted(() => load().catch((cause) => { error.value = errorMessage(cause) }))
async function decide(decision: 'approve' | 'reject') { if (!item.value) return; try { const response = await apiRequest<Approval>(`/admin/approval-requests/${item.value.approval_request_id}/decisions`, { method: 'POST', headers: { 'If-Match': etag.value, 'Idempotency-Key': createIdempotencyKey('approval') }, body: JSON.stringify({ decision, reason_code: decision === 'approve' ? 'verified' : 'rejected', reason: reason.value }) }, auth.accessToken); item.value = response.data; etag.value = response.headers.get('etag') ?? ''; message.value = '审批决定已记录，业务执行状态请继续在此跟踪。' } catch (cause) { error.value = errorMessage(cause) } }
</script>
<template><section v-if="item"><p class="eyebrow">审批申请 · {{ item.approval_request_id }}</p><h1>{{ item.approval_type }}</h1><p v-if="message" class="alert success">{{ message }}</p><p v-if="error" class="alert error">{{ error }}</p><div class="settings-grid"><article class="card"><h2>规范化对象</h2><dl><dt>动作</dt><dd>{{ item.action_code }}</dd><dt>目标</dt><dd>{{ item.target_type }} · {{ item.target_id }}</dd><dt>审批进度</dt><dd>{{ item.approved_count }}/{{ item.required_approval_count }}</dd><dt>状态</dt><dd>{{ item.status }}</dd><dt>过期</dt><dd>{{ item.expires_at }}</dd></dl></article><article class="card"><h2>影响与版本</h2><pre>{{ JSON.stringify(item.display_snapshot, null, 2) }}</pre><pre>{{ JSON.stringify(item.resource_versions, null, 2) }}</pre></article></div><form v-if="item.status === 'pending'" class="card" @submit.prevent><label>审批意见<textarea v-model="reason" required /></label><div class="actions"><button class="danger" :disabled="!reason" @click="decide('reject')">拒绝</button><button :disabled="!reason" @click="decide('approve')">批准</button></div></form></section></template>
