<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { createTool, createToolVersion, listTools, publishToolVersion, type ToolSummary } from '@/api/admin-ai'
import { errorMessage } from '@/api/http'
import PageState from '@/components/PageState.vue'
import { useAdminAuthStore } from '@/stores/admin-auth'
const auth = useAdminAuthStore(), items = ref<ToolSummary[]>([]), loading = ref(true), error = ref(''), notice = ref('')
const definition = reactive({ tool_code: '', server_code: 'catalog-mcp', risk_level: 'read' })
const draft = reactive({ tool_code: '', input_schema: '{\n  "type": "object",\n  "additionalProperties": false\n}', output_schema: '{\n  "type": "object"\n}', evaluation_report: '{\n  "passed": false\n}' })
const token = () => auth.accessToken!
async function load() { loading.value = true; try { items.value = (await listTools(token())).data.items } catch (cause) { error.value = errorMessage(cause) } finally { loading.value = false } }
async function addDefinition() { try { await createTool(definition, token()); notice.value = 'Tool Definition 已创建。'; definition.tool_code = ''; await load() } catch (cause) { error.value = errorMessage(cause) } }
async function addVersion() { try { await createToolVersion(draft.tool_code, { input_schema: JSON.parse(draft.input_schema), output_schema: JSON.parse(draft.output_schema), evaluation_report: JSON.parse(draft.evaluation_report) }, token()); notice.value = 'Tool Version 草稿已创建。'; await load() } catch (cause) { error.value = cause instanceof SyntaxError ? 'Schema 或评估报告不是有效 JSON。' : errorMessage(cause) } }
async function publish(item: ToolSummary) { if (!item.latest_version || !window.confirm('确认发起高风险 Tool 双人发布审批？评估硬门禁必须全部通过。')) return; try { const result = (await publishToolVersion(item.tool_code, item.latest_version, token())).data; notice.value = `审批 ${result.approval_request_id} 已创建，需 ${result.required_approval_count} 名独立管理员批准。`; await load() } catch (cause) { error.value = errorMessage(cause) } }
onMounted(load)
</script>
<template><section class="admin-page-stack"><header class="page-heading"><div><p class="eyebrow">MCP Contract</p><h1>MCP Tool 管理</h1><p class="muted">Tool Definition 不保存 Schema；输入输出 Schema、评估报告和发布状态属于不可变 Version。</p></div></header><p v-if="error" class="alert error">{{ error }}</p><p v-if="notice" class="alert success">{{ notice }}</p><div class="admin-split"><PageState :loading="loading" :error="''" :empty="!loading && items.length === 0" empty-title="暂无 Tool"><div class="card-list"><article v-for="item in items" :key="item.tool_code" class="card"><div class="card-heading"><div><h2>{{ item.tool_code }}</h2><p>{{ item.server_code }} · {{ item.risk_level }}</p></div><span class="badge">{{ item.status }}</span></div><p>最新 v{{ item.latest_version ?? '-' }} · 已发布 v{{ item.published_version ?? '-' }}</p><details v-if="item.input_schema"><summary>当前 Schema</summary><pre>{{ JSON.stringify({ input: item.input_schema, output: item.output_schema }, null, 2) }}</pre></details><button v-if="auth.has('ai_tools:publish') && item.latest_version !== item.published_version" @click="publish(item)">发布最新草稿</button></article></div></PageState><div class="card-list"><form v-if="auth.has('ai_tools:manage')" class="card admin-editor" @submit.prevent="addDefinition"><h2>新建 Definition</h2><label>Tool Code<input v-model="definition.tool_code" required></label><label>MCP Server<select v-model="definition.server_code"><option v-for="code in ['catalog-mcp','order-mcp','logistics-mcp','after-sale-mcp','support-mcp','memory-mcp']" :key="code">{{ code }}</option></select></label><label>风险<select v-model="definition.risk_level"><option v-for="risk in ['read','low','medium','high']" :key="risk">{{ risk }}</option></select></label><button>创建</button></form><form v-if="auth.has('ai_tools:manage')" class="card admin-editor" @submit.prevent="addVersion"><h2>新建不可变版本</h2><label>Tool<select v-model="draft.tool_code" required><option value="">请选择</option><option v-for="item in items" :key="item.tool_code">{{ item.tool_code }}</option></select></label><label>Input Schema<textarea v-model="draft.input_schema" required></textarea></label><label>Output Schema<textarea v-model="draft.output_schema" required></textarea></label><label>评估报告 JSON<textarea v-model="draft.evaluation_report" required></textarea></label><button>创建草稿版本</button></form></div></div></section></template>
